version: '3.8'

services:
  kafka:
    image: apache/kafka:4.1.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kafka-logs
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s
    networks:
      - general-network

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-listen-address="0.0.0.0:8200"
    volumes:
      - vault_data:vault/data

  db:
    image: postgres:17.5
    container_name: postgres
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5435
      POSTGRES_DB: recipe_service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - db-network
      - general-network

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch-recipe-service
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health | grep -q '\"status\":\"\\(green\\|yellow\\)\"' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 90s
    networks:
      - general-network

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-redispass123}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redispass123}", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - general-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass123}

  recipe-service:
    image: recipe-service:latest
    container_name: recipe-service
    restart: always
    build:
      context: ./recipe-service-api
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kafka:
        condition: service_healthy
      parser-service-api:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/recipe_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5435
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_ELASTICSEARCH_CONNECTION_TIMEOUT: 30000
      SPRING_ELASTICSEARCH_SOCKET_TIMEOUT: 40000
      ELASTICSEARCH_HOST_AND_PORT: elasticsearch:9200
      SPRING_DATA_ELASTICSEARCH_AUTO_CREATE_INDEX: "false"
      SPRING_DATA_ELASTICSEARCH_REPOSITORIES_ENABLED: "true"
    networks:
      - db-network
      - general-network

  parser-service-api:
    image: parser-service_api:latest
    container_name: parser-service
    restart: always
    build:
      context: ./parser-service-api
      dockerfile: ./Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - general-network

  frontend:
    container_name: recipe-aggregator-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - recipe-service
    environment:
      - REACT_APP_API_URL=http://recipe-service:8082

networks:
  db-network:
    driver: bridge
  general-network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:
  vault_data: