version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    healthcheck:
      test: [ "CMD", "zkServer.sh", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - kafka-network

  db:
    image: postgres:17.5
    container_name: RecipeAggregatorDb
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5435
      POSTGRES_DB: recipe_service
    networks:
      - db-network

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch-recipe-service
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - db-network

  recipe-service-api:
    image: recipe-service_api:latest
    container_name: recipe-service
    restart: always
    build:
      context: .
      dockerfile: recipe-service-api/Dockerfile
    depends_on:
      - db
      - kafka
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/recipe_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5435
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - db-network
      - kafka-network

  parser-service-api:
    image: parser-service_api:latest
    container_name: parser-service
    restart: always
    build:
      context: .
      dockerfile: parser-service-api/Dockerfile
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka-network

networks:
  db-network:
    driver: bridge
  kafka-network:
    driver: bridge
    name: kafka-network

volumes:
  postgres_data:
  elasticsearch_data: