server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/auth/**
              filters:
                - JwtAuthenticationFilter
                - StripPrefix=1

            - id: search-service
              uri: lb://search-service
              predicates:
                - Path=api/v1/search**
              filters:
                - JwtAuthenticationFilter
                - AddRequestHeader=X-Internal-Request, true
                - AddRequestHeader=X-Gateway-Secret, ${GATEWAY_SECRET}

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=api/v1/user/**
              filters:
                - JwtAuthenticationFilter
                - AddRequestHeader=X-Internal-Request, true
                - AddRequestHeader=X-Gateway-Secret, ${GATEWAY_SECRET}

  security:
    jwt:
      secret: ${GATEWAY_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway