spring:
  application:
    name: search_service_api
  datasource:
    url: jdbc:postgresql://localhost:5435/recipe_service
    username: postgres
    password: 5435
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql

springdoc:
  swagger-ui:
    path: "/swagger-recipe-aggregator"

application:
  rest:
    api:
      prefix: /api

server:
  port: 8087

elasticsearch:
  host-and-port: localhost:9200
