spring:
  application:
    name: parser-service-api
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redispass123}
      timeout: 10s
      connect-timeout: 10s
      ttl:
        recipe: 90
        urls: 90
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms
    cache:
      type: redis

recipe:
  cache:
    name: 'recipes'

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

custom-kafka:
  topic: recipes

parser:
  browser:
    mainUrl: https://www.allrecipes.com/recipes-a-z-6735880#alphabetical-list-a
    userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
    referrer: https://www:google:com
    headerAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    headerCookie: ${ALLRECIPES_COOKIE:}
  recipeTag: "html[id=recipeScTemplate_1-0]"
  timeoutMs: 15000
  minDelayMs: 1000
  maxDelayMs: 2000
  maxLinksPerPage: 50
  maxRecipes: 25
  maxDepth: 5
  containerSelectors: >
    div.mntl-alphabetical-list__group, 
    div.comp.mntl-universal-card-list,
    div.comp.mntl-taxonomysc-content,
    div.comp.mntl-taxonomy-nodes,
    div.comp.mntl-taxonomysc-article-list-group,
    div.comp.related-category-search__category-tags,
    div.comp.mntl-sc-block,
    div.comp.mntl-three-post__inner

logging:
  file:
    path: ./logs
    name: ./logs/parser-service.log
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
      total-size-cap: 5GB
      file-name-pattern: ${logging.file.path}/archived/parser_service.%d{yyyy-MM-dd}.log
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'