spring:
  application:
    name: parser-service-api
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

custom-kafka:
  topic: recipes

parser:
  browser:
    main-url: https://www.allrecipes.com/recipes-a-z-6735880#alphabetical-list-a
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
    referrer: https://www:google:com
    header-accept: ext/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    header-cookie: TMog=n41e40e2e5df14f10858cc8a6eb1abee013; globalTI_SID=481cf78f-0834-495a-8317-4614e15471b3; _lc2_fpi=6c17f56c0790--01k0pm2z5dx5arb4s81g5hma0g; _lc2_fpi_meta=%7B%22w%22%3A1753105923245%7D; _sharedid=d607c40d-240e-4498-9f05-2a7485d09523; _ga=GA1.1.1253635947.1753105923; _cc_id=267a26c2208d2d1c064c29146eff5e2b; _cb=BscnSHCb4qtMD59XNI; _fbp=fb.1.1753105924658.540247337246617665; dmd-tag=e1c3f410-6639-11f0-89d9-b3e2a85fc5ec; _li_ss=CrcBCgYI-QEQsRsKBgj3ARCwGwoFCAoQsBsKBgjdARCwGwoGCPgBELEbCgYIgQEQsBsKBQgMELAbCgYI9QEQsBsKBQgLELAbCgYI4wEQsRsKBgikARCxGwoGCLMBELEbCgYIiQEQsRsKBgilARCwGwoGCIACELIbCgYI4QEQsBsKBgiiARCwGwoGCP8BELAbCgkI_____wcQsBsKBgiHAhCwGwoGCNIBELAbCgUIfhCwGwoGCIgBELEb; OptanonAlertBoxClosed=2025-11-06T15:27:56.368Z; eupubconsent-v2=CQadUwgQadUwgAcABBENCDFgAP_gAEPgAAYgJ0gBxC5MAAFCaCB2AIoEMAQGwBBAQEAgAAAAAAABABIAAAwAAEARAASIAAACGAAAIAAAAAAAAAAAAEAAIAAAAABAAEAAAAAAIAAAAAAAAEAIAAAgAAAgEAAAAAAQEAQAiAAEAIIAAEgAAAAAAAAAIAAEABAAAAAAAAAAQAAAAQAAACgAgAAAAAAAAAAAABAEAAEAAAAAAAAAAAAAAAACCdMCEABYAFQALgAcABAADIAGgAPAAmABoAD8AIQARwAnABWgDugIOAhABFgCOAEmAJoAT8Az4BrwDiAKlAXmAywB_YEEwJZgTlAnSAAA.f_wACHwAAAAA; OTGPPConsent=DBABMA~CQaf3DcQaf3DcAcABBENCDFgAP_gAEPgAAYgJ0gBxC5MAAFCaCB2AIoEMAQGwBBAQEAgAAAAAAABABIAAAwAAEARAASIAAACGAAAIAAAAAAAAAAAAEAAIAAAAABAAEAAAAAAIAAAAAAAAEAIAAAgAAAgEAAAAAAQEAQAiAAEAIIAAEgAAAAAAAAAIAAEABAAAAAAAAAAQAAAAQAAACgAgAAAAAAAAAAAABAEAAEAAAAAAAAAAAAAAAACCdMCEABYAFQALgAcABAADIAGgAPAAmABoAD8AIQARwAnABWgDugIOAhABFgCOAEmAJoAT8Az4BrwDiAKlAXmAywB_YEEwJZgTlAnSAAA.f_wACHwAAAAA; _sharedid_cst=7yzaLJcslw%3D%3D; _lr_env_src_ats=false; FCCDCF=%5Bnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C%5B%5B32%2C%22%5B%5C%2298e9eebc-7c9a-4552-99a9-719e309dab63%5C%22%2C%5B1761827231%2C766000000%5D%5D%22%5D%5D%5D; FCNEC=%5B%5B%22AKsRol-F4q6fLICamRYbnyXzff3gmyaLsce_sHogX-k95y04gM680lnLJoKToI0IBbIdpuIYsGlGkfvSAWe2r23ZHJUi9Riz6dJCYoozWti_maZBX9OPM3JGHhp8XA_a3Ca9LvnXKBn_q2pObyQopfgq-tsdND4rXw%3D%3D%22%5D%5D; __cf_bm=xTS.9aRag4tVfSuU9lmTdQxonMx400NdZUTZACuEPpo-1763564617-1.0.1.1-yM8oKxA8JLp49d4H.OuBsZ2eFFYarX.tQ6qlJ8ZXrWM6eLQTfNmnGYuXpvTih9dRjj8pFL4niXw7MypLyPyY.3pzklH6JHQK_FOdn2UKZSo1nrq_9nQot9Begv6xwCEi; _cfuvid=qebM4yQbnQTeYOtFy7QNxpVmWAt_oOGtdoU9uSphEWw-1763564619208-0.0.1.1-604800000; cf_clearance=oODDcNKIQSiPI6FVyqDhcfro4NwGXiEwkMSfgnU_zVg-1763564626-1.2.1.1-iObmq3wf5HoFwj4KSGn3UWlQSja9rsMsPD6ph1CM8dx4RG5P0AUt6.Udby4nN6U2a8MtlIRPpMVAvCnDCXDZ29eLuKNpDrLRLFYjahfCY53OKffx_zyRa6F6Ho9hynRPcmWKPLpSyeK7lqe3m8zBnFMr2vtTXh7IsXx.7JWHfaz3_CW889Kj2_N4u6nHIoUbZJMhdYPg_746Sp8DnT82aiqCS2lwM8TUPYTRRLGZheY; Mint=n9ecb0537cfcf4157aee12c4dd23b386115; CSRFToken=5df559072d024a01e1ca658f1151355e; lb_ld=search; _lr_retry_request=true; _li_dcdm_c=.allrecipes.com; _cb_svref=https%3A%2F%2Fwww.google.com%2F; _sharedID=4e2fbd06-eeac-4357-bfc6-3ccd12e444a1; _sharedID_cst=7yzaLJcslw%3D%3D; _chartbeat2=.1753105924422.1763565588588.0010000000000001.BGJ7aQWVXvN7vcsvPTcA7DZa0AO.8; dmd-sid4={%22id%22:%22f8225980-c558-11f0-be08-8d1bc39e74f1%22%2C%22timestamp%22:1763564634000%2C%22lastUpdate%22:1763565587000}; panoramaId_expiry=1763651990908; panoramaId=2331f5cfe21fb53e96258b50f9b5a9fb927acc31984d63928198f52ae1c80395; panoramaIdType=panoDevice; _lr_sampling_rate=100; __gads=ID=4e3a919e9b4dada8:T=1753105922:RT=1763565593:S=ALNI_MYYgI6BTRkgJ76bCUZs8hF207czeA; __gpi=UID=000010f29e4c6956:T=1753105922:RT=1763565593:S=ALNI_MbtoAxnMCIz9ueGC0yv5590rskyeg; __eoi=ID=816b8fd29f3c103c:T=1753105922:RT=1763565593:S=AA-AfjYxh1vNqDyfQMKErFBTHDX-; _pn=eyJzdWIiOnsidWRyIjowLCJpZCI6ImVSUzNzWkhHVFVCQUlIOURSR2E4NWliWlY0TmlTNm9wIiwic3MiOi0xLCJkc2UiOjE3NjQxNjk3MDE1MzJ9LCJsdWEiOjE3NjM1NjU1OTkzNTl9; _SUPERFLY_lockout=1; _ga_9D9M6LNQMD=GS2.1.s1763564631$o16$g1$t1763565930$j6$l0$h0; _ga_DK3GDWHWJH=GS2.1.s1763564631$o8$g1$t1763565930$j6$l0$h0; _chartbeat4=t=CseB3qtT7-8D0AkHDBporjHD3y_vQ&E=0&x=0&c=5.71&y=16939&w=1017; session_depth=www.allrecipes.com%3D4%7C438581382%3D4; OptanonConsent=isGpcEnabled=0&datestamp=Wed+Nov+19+2025+18%3A26%3A08+GMT%2B0300+(%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C+%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%BE%D0%B5+%D0%B2%D1%80%D0%B5%D0%BC%D1%8F)&version=202505.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=ad4b0575-e10d-4377-aab2-08c9396b092d&interactionCount=2&isAnonUser=1&landingPath=NotLandingPage&GPPCookiesCount=1&AwaitingReconsent=false&groups=2%3A1%2C4%3A1%2C1%3A1%2C3%3A1&intType=1&geolocation=GB%3B; cto_bundle=R26FnF84S09HMXI2SkxabXVKMXJBU3ZYWGdzQm5OTExURTROUmhnZmw2SXhqQjQ3b3o4V1hzaTNkOWI3U0pkcnlTOTdXYngyUHI1RnN2T2lVVlUlMkJ5ZE4lMkJFR2lwSUxwMFZDc2lqVWtVWUdMY2YlMkIxV3BWbm0xbDd0NUFxbkVnMlFlMW80YjNSbXpxJTJGVUlUbWQ4WGhRbXhuT3Bxc0tpTjRDR1FSRkJLMWFnWlR4OXBzcyUzRA; cto_bidid=lQaxtV96T2k0S1VxSG0weUFBS2hpQVRORkVFMjBNRTNWYVlFUThBUkx6TmhpWkNzOGQzWktCazI5WHgyUjdEdjFHelRYcUl3WEolMkZ2Z1hsciUyQkFjRkFNbU9NR3BFbE5yT1M2cWQ3JTJGZ000NFI4UElWakh5dXEzbENOZFBPTSUyRjhCelI2SXk2
  recipe-tag: "html[id=recipeScTemplate_1-0]"
  timeout: 15000
  min-delay-ms: 1000
  max-delay-ms: 2000
  max-links-per-page: 50
  max-recipes: 5
  max-depth: 5
  container-selectors: >
    div.mntl-alphabetical-list__group, 
    div.comp.mntl-universal-card-list,
    div.comp.mntl-taxonomysc-content,
    div.comp.mntl-taxonomy-nodes,
    div.comp.mntl-taxonomysc-article-list-group,
    div.comp.related-category-search__category-tags,
    div.comp.mntl-sc-block,
    div.comp.mntl-three-post__inner

logging:
  file:
    path: ./logs
    name: ./logs/parser-service.log
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
      total-size-cap: 5GB
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'